//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hacktice {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hacktice.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] data {
            get {
                object obj = ResourceManager.GetObject("data", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;&lt;!--Generic XML patch (Generated by Simple Armips GUI)--&gt;&lt;patch&gt;&lt;data&gt;&lt;address&gt;0x396C&lt;/address&gt;&lt;bytes&gt;0x3C,0x04,0x80,0x05,0x24,0x84,0xD2,0x00,0x3C,0x05,0x00,0x7F,0x24,0xA5,0x12,0x00,0x3C,0x06,0x00,0x80,0x0C,0x09,0xE1,0x41,0x00,0x00,0x00,0x00,0x0C,0x01,0x34,0x80,0x00,0x00,0x00,0x00&lt;/bytes&gt;&lt;/data&gt;&lt;data&gt;&lt;address&gt;0x4688&lt;/address&gt;&lt;bytes&gt;0xA0,0x3B,0xB2,0x5E&lt;/bytes&gt;&lt;/data&gt;&lt;data&gt;&lt;address&gt;0x4694&lt;/address&gt;&lt;bytes&gt;0x00,0x00,0x00,0x00&lt;/bytes&gt;&lt;/data&gt;&lt;data&gt;&lt;address&gt;0x5024&lt;/address&gt;&lt;bytes&gt;0x10,0x00,0x0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hook {
            get {
                return ResourceManager.GetString("hook", resourceCulture);
            }
        }
    }
}
